/**
 * Theme Studio serializer — a derived token map → a valid `themes/<name>.css`
 * text. Pure, fs-free: it returns the string; writing it to disk (graduation)
 * or registering it via `PG.addThemes([cssText])` (live preview) is the
 * caller's job.
 *
 * The emitted file follows the anatomy in design/theming.md: the `@theme`
 * directive + `@size` map, `@import 'lattice'`, the zero-specificity light
 * default, then grouped `:root` blocks (surfaces/ink/accent/semantic, the
 * dark-variant band, hljs, categorical, chart-family). Tokens not present in
 * the map are simply omitted — derivation guarantees the required set, so a
 * round-trip parse sees every contract token.
 */

const { REQUIRED_TOKENS } = require('./derive.js');

const SIZE_BLOCK = ` * @size hd       1280px 720px
 * @size HD       1280px 720px
 * @size 4K       3840px 2160px
 * @size 4k       3840px 2160px
 * @size standard 960px  720px
 * @size 16:9     1280px 720px
 * @size square   1080px 1080px
 * @size 1:1      1080px 1080px
 * @size portrait 1080px 1350px
 * @size 4:5      1080px 1350px
 * @size story    1080px 1920px
 * @size reel     1080px 1920px
 * @size 9:16     1080px 1920px
 * @size mobile   1080px 2340px`;

/** One `--name: value;` line, indented two spaces. */
function decl(map, name) {
  if (map[name] == null) return null;
  return `  --${name}: ${map[name]};`;
}

/** A `:root { … }` block from a list of token names; omits absent tokens. */
function rootBlock(map, names, heading) {
  const lines = names.map(n => decl(map, n)).filter(Boolean);
  if (lines.length === 0) return '';
  const head = heading ? `  /* ${heading} */\n` : '';
  return `:root {\n${head}${lines.join('\n')}\n}`;
}

/**
 * Serialize a derived token `map` to theme CSS.
 * @param {object} map   flat token map (names without `--`), e.g. deriveTheme()
 * @param {object} opts  { name, label, description }
 * @returns {string} CSS text suitable for `themes/<name>.css`
 */
function serializeTheme(map, { name, label, description } = {}) {
  if (!name || !/^[a-z][a-z0-9-]*$/.test(name)) {
    throw new Error(`theme name must be a lowercase slug, got: ${name}`);
  }
  const title = label || name;
  const desc = description || 'Generated by the Lattice Workbench (Theme Studio).';

  const header = `/* @theme ${name}
 *
${SIZE_BLOCK}
 *
 * Lattice · ${title}
 * ${'─'.repeat(72)}
 * ${desc}
 *
 * Token-only palette on the Lattice contract (design/theming.md). Surfaces,
 * ink, and accent are light-dark() pairs so the dark variant works from the
 * native color-scheme cascade — no per-variant file required. Every
 * text-bearing token clears WCAG AA on its paired surface in both modes
 * (derived contrast-aware; verify with \`npm run test:palette\`).
 */`;

  const blocks = [
    header,
    "@import 'lattice';",
    '/* Zero-specificity light default — author overrides always win. */\n:where(:root) { color-scheme: light; }',
    rootBlock(map, [...REQUIRED_TOKENS.surfaces, ...REQUIRED_TOKENS.ink, ...REQUIRED_TOKENS.accent, ...REQUIRED_TOKENS.semantic], 'Surfaces · ink · accent · semantic signals'),
    rootBlock(map, REQUIRED_TOKENS.dark, 'Dark-variant tokens (section.dark + light-dark() dark sides)'),
    rootBlock(map, REQUIRED_TOKENS.hljs, 'highlight.js syntax'),
    rootBlock(map, [...REQUIRED_TOKENS.categorical, ...REQUIRED_TOKENS.universal], 'Categorical cycle (paired light/dark) + structural + alarm'),
    rootBlock(map, REQUIRED_TOKENS.chart, 'Chart-family spectrums'),
  ].filter(Boolean);

  return `${blocks.join('\n\n')}\n`;
}

/**
 * The in-browser asset record for a crafted theme (the `kind:'theme'` shape
 * from the asset note). Pure: shaping only — persisting it (IndexedDB) is the
 * caller's job. Library-scoped by default (`deckId:null`), provenance `studio`.
 * Carries both the serialized `text` (drop-in CSS) and the `essentials` so the
 * studio can load it back for editing.
 */
function themeAsset({ name, label, essentials, css } = {}, { id, deckId = null, provenance = 'studio' } = {}) {
  if (!name || !/^[a-z][a-z0-9-]*$/.test(name)) {
    throw new Error(`theme name must be a lowercase slug, got: ${name}`);
  }
  return {
    ...(id ? { id } : {}),
    deckId,
    kind: 'theme',
    name,
    label: label || name,
    text: String(css || ''),
    essentials: essentials || null,
    provenance,
    addedAt: Date.now(),
  };
}

module.exports = { serializeTheme, themeAsset };
