// Auto-generated by tools/build-marp-kit.js — the Lattice copy-and-go kit.
const path = require('path');
// Both files must be registered: a palette `@import 'lattice'` BY NAME, and
// only Marp's theme set resolves that. Registering the palette alone yields
// unstyled slides with no error.
module.exports = {
  themeSet: [
    path.join(__dirname, 'lattice.min.css'),
    path.join(__dirname, 'cuoio.min.css'),
    path.join(__dirname, 'cuoio-dark.min.css'),
  ],
  allowLocalFiles: true,
  // marp-core escapes raw HTML by default; without this the deck's runtime
  // <script> tags render as visible text and no chart or diagram is built.
  html: true,
};
