/**
 * Integration: per-bucket survey gallery PDFs match the manifest
 * partition.
 *
 * Each bucket has two committed PDFs:
 *   lib/components/<bucket>/<bucket>.gallery.{light,dark}.pdf
 *
 * The PDF page count must equal the number of components in the
 * bucket plus 1 (the title slide). This catches:
 *   - A new component added to a bucket without rebuilding the
 *     bucket gallery.
 *   - A component removed from a bucket while the stale PDF lingers.
 *   - A composition bug that drops a slide under the dark variant.
 *
 * The bucket-gallery source .md is also asserted to be up to date
 * against what composeBucketGallery() would emit from the current
 * manifest set — same "regenerate vs check" contract that the
 * per-component docs/gallery test uses.
 *
 * Bucket galleries are generated by tools/build-bucket-galleries.js
 * (`npm run build:bucket-galleries`). See docs/notes/2026-05-18-
 * component-reorg-and-modular-css.md (Phase 5).
 */

const { test, describe } = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const { loadAll, groupByBucket, BUCKETS } = require('../../../lib/components');
const {
  composeBucketGallery,
  bucketGalleryMarkdownPath,
  bucketGalleryPdfPath,
  isBucketGalleryAuthored,
} = require('../../../tools/build-bucket-galleries');
const { pageCount } = require('../../helpers/pdf');

describe('bucket-galleries', () => {
  const groups = groupByBucket(loadAll());

  for (const bucket of BUCKETS) {
    const manifests = groups[bucket] || [];
    const authored = isBucketGalleryAuthored(bucket);

    test(
      `${bucket}: source .md matches manifests`,
      {
        timeout: 30000,
        skip: authored
          ? `${bucket} bucket gallery is hand-authored (galleryAuthored marker)`
          : false,
      },
      () => {
        if (manifests.length === 0) return;
        const mdPath = bucketGalleryMarkdownPath(bucket);
        assert.ok(
          fs.existsSync(mdPath),
          `bucket gallery missing: ${path.relative(process.cwd(), mdPath)} — run \`npm run build:bucket-galleries\``,
        );
        const actual = fs.readFileSync(mdPath, 'utf8');
        const expected = composeBucketGallery(bucket, manifests);
        assert.equal(
          actual,
          expected,
          `${bucket} gallery .md drifted from manifests — re-run \`npm run build:bucket-galleries\``,
        );
      },
    );

    for (const theme of ['light', 'dark']) {
      test(
        `${bucket}: ${theme} PDF page count = members + 1 (title slide)`,
        {
          timeout: 30000,
          // Hand-authored galleries don't follow the
          // members+1 formula — their slide count is whatever the
          // author chose. The light/dark parity assertion below
          // still catches transforms that drop slides under dark.
          skip: authored
            ? `${bucket} bucket gallery is hand-authored (page count not derived from manifest)`
            : false,
        },
        () => {
          if (manifests.length === 0) return;
          const pdfPath = bucketGalleryPdfPath(bucket, theme);
          assert.ok(
            fs.existsSync(pdfPath),
            `bucket gallery PDF missing: ${path.relative(process.cwd(), pdfPath)} — run \`npm run build:bucket-galleries\``,
          );
          // Title slide + one slide per component that has a `sample`.
          const componentsWithSample = manifests.filter((m) => typeof m.sample === 'string' && m.sample.trim()).length;
          const expectedPages = 1 + componentsWithSample;
          assert.equal(
            pageCount(pdfPath),
            expectedPages,
            `${bucket}.gallery.${theme}.pdf page count diverged from manifest membership`,
          );
        },
      );
    }

    if (authored && manifests.length > 0) {
      test(
        `${bucket}: hand-authored dark page count matches light`,
        { timeout: 30000 },
        () => {
          const lightPath = bucketGalleryPdfPath(bucket, 'light');
          const darkPath = bucketGalleryPdfPath(bucket, 'dark');
          assert.ok(fs.existsSync(lightPath), `missing: ${lightPath}`);
          assert.ok(fs.existsSync(darkPath), `missing: ${darkPath}`);
          assert.equal(
            pageCount(darkPath),
            pageCount(lightPath),
            `${bucket}.gallery.dark.pdf diverged from light page count — a transform may be dropping a slide`,
          );
        },
      );
    }
  }
});
