/**
 * Integration: rebuild lib/integrations/mermaid/mermaid.gallery.md
 * through the lattice emulator and assert the produced PDF matches
 * the expected page count.
 *
 * Very slow on cache miss (~2 minutes — 25 mmdc cold starts via
 * Puppeteer); instant on hit. Lives under test/integration; CI runs
 * it, the inner-loop `npm test` does not.
 *
 * Source moved from examples/gallery-mermaid.md → lib/integrations/
 * mermaid/mermaid.gallery.md in Phase 7b of the component-reorg work
 * (integration showcase belongs with the integration). The light PDF
 * is committed alongside the .md; the dark sibling is generated by
 * tools/build-galleries.js (Phase 7b extension).
 */

const { test, describe } = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const { runEmulator } = require('../../helpers/render');
const { pageCount }   = require('../../helpers/pdf');

const MERMAID_GALLERY = path.join(
  __dirname, '..', '..', '..', 'lib', 'integrations', 'mermaid', 'mermaid.gallery.md',
);
const EXPECTED_PAGES = 31;

describe('emulator.gallery-mermaid', () => {
  test('emulator: mermaid.gallery.md builds and produces expected page count',
    { timeout: 600000 },
    () => {
      const pdf = runEmulator(MERMAID_GALLERY);
      assert.equal(pageCount(pdf), EXPECTED_PAGES,
        'mermaid.gallery.md page count drifted');
    });
});
