/**
 * Unit: Export to Marp (tools/export-marp.js).
 *
 * Covers the pure helpers (front-matter theme read, asset localization) and an
 * end-to-end bundle: the exporter produces the expected layout, and the baked
 * deck.md divides into the same slides as the source — the portability contract.
 */

const { test, describe, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const REPO = path.join(__dirname, '..', '..', '..');
const TOOL = path.join(REPO, 'tools', 'export-marp.js');
const { localizeAssets, readTheme } = require(TOOL);
const latticeEngine = require('../../../lib/engine');

describe('export-marp helpers', () => {
  test('readTheme reads the front-matter palette, or null', () => {
    assert.equal(readTheme('---\nmarp: true\ntheme: cuoio\n---\n\n# A'), 'cuoio');
    assert.equal(readTheme('# A\n\nno front matter'), null);
  });

  test('localizeAssets copies local images + rewrites paths; leaves remote alone', () => {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'exp-loc-'));
    const deckDir = path.join(tmp, 'src');
    fs.mkdirSync(deckDir);
    fs.writeFileSync(path.join(deckDir, 'logo.png'), 'PNGDATA');
    const dest = path.join(tmp, 'out');
    fs.mkdirSync(dest);
    const body = '![logo](logo.png)\n\n![remote](https://x/y.png)\n\n![missing](nope.png)';
    const { body: out, count } = localizeAssets(body, deckDir, dest);
    assert.match(out, /!\[logo\]\(assets\/logo\.png\)/, 'local image rewritten to assets/');
    assert.match(out, /!\[remote\]\(https:\/\/x\/y\.png\)/, 'remote URL untouched');
    assert.match(out, /!\[missing\]\(nope\.png\)/, 'dangling ref left as-is');
    assert.equal(count, 1);
    assert.ok(fs.existsSync(path.join(dest, 'assets', 'logo.png')), 'image copied into assets/');
    fs.rmSync(tmp, { recursive: true, force: true });
  });
});

describe('export-marp bundle (end-to-end)', () => {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'exp-e2e-'));
  let dest;
  before(() => {
    execFileSync('node', [TOOL, path.join(REPO, 'examples', 'split-headings.md'), tmp], { stdio: 'pipe' });
    dest = path.join(tmp, 'split-headings');
  });
  after(() => fs.rmSync(tmp, { recursive: true, force: true }));

  test('produces the expected Marp-native bundle layout', () => {
    for (const f of [
      'split-headings.md', 'README.md', 'marp.config.cjs', 'package.json',
      '.vscode/settings.json',
      'lattice.css', 'themes/indaco.css', 'themes/indaco-dark.css',
      'mermaid-v11.min.js', 'lattice-runtime.min.js',
    ]) {
      assert.ok(fs.existsSync(path.join(dest, f)), `bundle is missing ${f}`);
    }
    // No emulator / dist/ folder — the bundle is rendered with Marp.
    assert.ok(!fs.existsSync(path.join(dest, 'dist')), 'bundle must not ship a dist/ folder');
    assert.ok(!fs.existsSync(path.join(dest, 'dist', 'lattice-emulator.js')), 'no bundled emulator');
  });

  test('bundled themes are the minified build; .vscode registers them', () => {
    const carta = fs.readFileSync(path.join(dest, 'themes', 'indaco.css'), 'utf8');
    assert.match(carta, /GENERATED by tools\/build-css\.js \(minified\)/, 'theme is the minified dist build');
    assert.match(carta, /@theme indaco/, 'minified theme keeps its @theme name');
    const settings = JSON.parse(fs.readFileSync(path.join(dest, '.vscode', 'settings.json'), 'utf8'));
    assert.deepEqual(settings['markdown.marp.themes'],
      ['lattice.css', 'themes/indaco.css', 'themes/indaco-dark.css']);
  });

  test('deck ends with the runtime scripts (browser render) under a lint-ignore', () => {
    const baked = fs.readFileSync(path.join(dest, 'split-headings.md'), 'utf8');
    assert.match(baked, /<!-- markdownlint-disable MD033 -->\n<script src="mermaid-v11\.min\.js"><\/script>\n<script src="lattice-runtime\.min\.js"><\/script>\s*$/,
      'markdown ends with the lint-ignore + mermaid + runtime script tags');
  });

  test('baked deck.md states split: rule and divides into the same slides', () => {
    const baked = fs.readFileSync(path.join(dest, 'split-headings.md'), 'utf8');
    assert.match(baked, /split: rule/, 'splits are baked → split: rule');
    const original = fs.readFileSync(path.join(REPO, 'examples', 'split-headings.md'), 'utf8');
    const engine = latticeEngine.createEngine();
    const count = (src) => (engine.render(src).html.match(/<section[\s>]/g) || []).length;
    assert.equal(count(baked), count(original), 'baked deck divides identically to the source');
  });

  test('package.json pins marp-cli only', () => {
    const pkg = JSON.parse(fs.readFileSync(path.join(dest, 'package.json'), 'utf8'));
    assert.ok(pkg.dependencies['@marp-team/marp-cli']);
    // No @slidewright/lattice dep — it is unpublished, so it would 404 `npm
    // install`; the bundle is rendered with Marp, not a bundled engine.
    assert.strictEqual(pkg.dependencies['@slidewright/lattice'], undefined);
  });

  test('ships the agent kit by default (AGENTS.md + the catalog under agent/)', () => {
    assert.ok(fs.existsSync(path.join(dest, 'AGENTS.md')), 'AGENTS.md present');
    const cat = path.join(dest, 'agent', 'components.json');
    assert.ok(fs.existsSync(cat), 'agent/components.json present');
    const agents = fs.readFileSync(path.join(dest, 'AGENTS.md'), 'utf8');
    assert.match(agents, /split-headings\.md/, "AGENTS.md names this bundle's deck");
    assert.match(agents, /agent\/components\.json/);
    assert.match(agents, /capacity/i);
    const catalog = JSON.parse(fs.readFileSync(cat, 'utf8'));
    assert.ok(Array.isArray(catalog.components) && catalog.components.length > 0, 'catalog has components');
    assert.match(fs.readFileSync(path.join(dest, 'README.md'), 'utf8'), /Extend it with an AI agent/);
  });

  test('--no-agent produces a lean Marp-only bundle', () => {
    const lean = fs.mkdtempSync(path.join(os.tmpdir(), 'exp-lean-'));
    execFileSync('node', [TOOL, path.join(REPO, 'examples', 'split-headings.md'), lean, 'indaco', '--no-agent'], { stdio: 'pipe' });
    const d = path.join(lean, 'split-headings');
    assert.ok(fs.existsSync(path.join(d, 'README.md')), 'still a valid bundle');
    assert.ok(!fs.existsSync(path.join(d, 'AGENTS.md')), 'no AGENTS.md');
    assert.ok(!fs.existsSync(path.join(d, 'agent')), 'no agent/ folder');
    assert.doesNotMatch(fs.readFileSync(path.join(d, 'README.md'), 'utf8'), /Extend it with an AI agent/);
    fs.rmSync(lean, { recursive: true, force: true });
  });
});
