#!/usr/bin/env node
/**
 * Map staged file paths → the npm test scripts that cover them.
 * Spawns each matching script in turn and exits non-zero on the first
 * failure. Used by the lefthook pre-commit hook for fast inner-loop
 * iteration; the full unit suite still runs in pre-push and CI.
 *
 * Safety: when a staged file isn't recognised, falls back to running
 * the full unit suite (`npm test`). Better to be slow than to miss a
 * regression.
 *
 * Usage:
 *   node tools/affected-tests.js <file>...
 *
 * Output:
 *   one line per script invoked, then the script's own output.
 */

const path = require('path');
const { spawnSync } = require('child_process');

// lib/<file>.js → scoped test script. Add new lib files here as they land.
// Note: per-component transforms now live at
// lib/components/<name>/transform.js — those are matched by the
// `lib/components/<name>/` rule below, not this table. Only files that
// remain at lib/ root after the component-folder migration belong here.
const SCRIPT_FOR_LIB = {
  'palette.js':           'test:palette',
  'resolve-palette.js':   'test:palette',
  'chart-family.js':      'test:components',
  'match-section.js':     'test:parsing',
  'slot-label-lift.js':   'test:parsing',
  'split-slides.js':      'test:parsing',
  'resolve-split.js':     'test:parsing',
  // The deck-lint engine + its Node binding — covered by lint-deck.test.js +
  // lint-core.test.js, both under test/unit/components/.
  'lint.js':              'test:components',
  'lint-core.js':         'test:components',
  // Presentation review heuristics + scorecard (Architect coach) — covered by
  // review-scorecard.test.js under test/unit/components/.
  'review-core.js':       'test:components',
  'scorecard.js':         'test:components',
  // Prose-density budgets (phase 2 of the capacity contract) — covered by
  // prose-budgets.test.js + review-scorecard.test.js under test/unit/components/.
  'prose-budgets.js':     'test:components',
};

// Cross-cutting files: changing any of these can affect every test.
// Fall back to the full unit suite.
//
// lattice-runtime.js is the esbuild BUNDLE OUTPUT (source lives at
// lib/runtime/index.js); it's regenerated by npm run runtime:build and
// covered by the runtime-bundle-freshness pre-commit hook, so a staged
// change to it on its own doesn't require running tests. Source-side
// changes under lib/runtime/** trigger the bundle rebuild AND the
// transformer test scope via the rule below.
const FULL_SUITE_TRIGGER = new Set([
  'lattice-emulator.js',
  'dist/lattice.css',
  'mermaid-v11.min.js',
  'package.json',
  'package-lock.json',
  'biome.json',
  'jsconfig.json',
]);

// Files that are pure infrastructure and never touch test outcomes.
// Skip silently — no tests need to run for these.
function isSkippable(rel) {
  return rel.startsWith('docs/')
      || rel.startsWith('engineering/')
      || rel.startsWith('design/')
      || rel.startsWith('examples/')
      || rel.startsWith('.scratch/')
      || rel.startsWith('.github/')
      || rel.endsWith('.md')
      || rel.endsWith('.pdf')
      || rel === '.nvmrc'
      || rel === '.gitignore'
      || rel === 'lefthook.yml'
      || rel === '.c8rc.json'
      // dist/lattice-runtime.js is a build artifact — regenerated by
      // npm run runtime:build, gated by the runtime-bundle-freshness
      // hook. Tests of its sources fire via lib/runtime/** below.
      || rel === 'dist/lattice-runtime.js'
      || rel.startsWith('tools/check-commit-msg')
      || rel.startsWith('tools/affected-tests');
}

const scripts = new Set();
let runAll = false;

for (const f of process.argv.slice(2)) {
  const rel = f.replace(/^\.\//, '');
  if (isSkippable(rel)) continue;

  if (FULL_SUITE_TRIGGER.has(rel)) { runAll = true; break; }

  // lib/components/<name>/* — component-folder migration target.
  // Manifest / styles / transform / example / README all belong to one
  // component; component-manifest + per-transform tests cover the lot.
  if (rel.startsWith('lib/components/') && !rel.endsWith('index.js')) {
    scripts.add('test:components');
    continue;
  }
  // lib/components/index.js — the loader + vocabularies. Cross-cutting.
  if (rel === 'lib/components/index.js') {
    scripts.add('test:components');
    continue;
  }

  // lib/transformers/* — shared transformer registry consumed by
  // lattice-emulator.js and the runtime bundle.
  if (rel.startsWith('lib/transformers/') && rel.endsWith('.js')) {
    scripts.add('test:transformers');
    continue;
  }

  // lib/runtime/* — runtime source bundled into lattice-runtime.js.
  // Tests of the bundled DOM transforms live in test:transformers.
  if (rel.startsWith('lib/runtime/') && rel.endsWith('.js')) {
    scripts.add('test:transformers');
    continue;
  }

  // lib/theme/* — the Theme Studio deterministic core (colour math, token
  // derivation, serialization, contrast audit, starters). Palette-shaped;
  // covered by the theme-*.test.js files under test/unit/palette/.
  if (rel.startsWith('lib/theme/') && rel.endsWith('.js')) {
    scripts.add('test:palette');
    continue;
  }

  // lib/<file>.js (top-level shared infrastructure)
  if (rel.startsWith('lib/') && rel.endsWith('.js')) {
    const script = SCRIPT_FOR_LIB[path.basename(rel)];
    if (script) scripts.add(script);
    else runAll = true;  // unknown lib file → safe default
    continue;
  }

  // lib/<file>.css — top-level shared stylesheet. Visual change, not
  // a unit-test concern; integration tier catches drift in CI.
  if (rel.startsWith('lib/') && rel.endsWith('.css')) continue;

  // test/unit/<scope>/*.test.js → run that scope
  const m = rel.match(/^test\/unit\/([^/]+)\//);
  if (m) { scripts.add(`test:${m[1]}`); continue; }

  // test/integration/* — pre-commit doesn't run integration; defer to CI
  if (rel.startsWith('test/integration/')) continue;

  // test/helpers/* or test/fixtures/* — affect multiple test files. Run all.
  if (rel.startsWith('test/')) { runAll = true; break; }

  // themes/*.css → palette tests
  if (rel.startsWith('themes/') && rel.endsWith('.css')) {
    scripts.add('test:palette');
    continue;
  }

  // tools/*.js — most are author tools, but anything imported by tests
  // would be flagged here. Conservative: full suite for unknown tool changes.
  if (rel.startsWith('tools/')) { runAll = true; break; }

  // Anything we don't recognise → safe default
  runAll = true;
  break;
}

const toRun = runAll ? ['test'] : [...scripts];

if (toRun.length === 0) {
  // No JS/test/theme changes — nothing to verify.
  process.exit(0);
}

console.log(`affected-tests: running ${toRun.join(', ')}`);

for (const script of toRun) {
  const r = spawnSync('npm', ['run', '--silent', script], { stdio: 'inherit' });
  if (r.status !== 0) process.exit(r.status);
}
