#!/usr/bin/env node
/**
 * Build the browser runtime bundle.
 *
 *   lib/runtime/index.js  →  dist/lattice-runtime.js
 *
 * The output path is a public API — committed decks embed
 * <script src="…/dist/lattice-runtime.js">, the README documents it, and
 * external consumers reference it via raw GitHub / jsdelivr URLs.
 * Changing the output path is a breaking change. See
 * reference/notes/2026-05-17-shared-transformer-registry.md (esbuild section)
 * for the rationale.
 *
 * Default build:  unminified IIFE + inline source map. Suitable for
 *                 marp-vscode preview, web export, and human inspection
 *                 in DevTools.
 *
 * Flags:
 *   --watch       Rebuild on source change. Used by npm run preview:watch.
 *   --check       Build to a temp file and diff against the committed
 *                 lattice-runtime.js. Exits 1 on drift. Used by the
 *                 bundle-freshness pre-commit hook.
 *   --silent      Suppress success log line (used by --check + hooks).
 *
 * Target: chrome91+. The marp-vscode preview webview runs on a Chromium
 * version a few major releases behind stable; we keep the bundle below
 * features that have caused trouble there (see reference/engineering/gotchas.md
 * for the ":not(:has(...))" case).
 */

const esbuild = require('esbuild');
const path    = require('path');
const fs      = require('fs');
const { execSync } = require('child_process');

const ROOT       = path.resolve(__dirname, '..');
const ENTRY      = path.join(ROOT, 'lib', 'runtime', 'index.js');
const OUT_FILE   = path.join(ROOT, 'dist', 'lattice-runtime.js');

const argv    = process.argv.slice(2);
const watch   = argv.includes('--watch');
const check   = argv.includes('--check');
const silent  = argv.includes('--silent') || check;

const BUILD_OPTIONS = {
  entryPoints: [ENTRY],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['chrome91'],
  // Sourcemap inlined so a single committed file covers debugging in
  // DevTools without needing a separate .map artifact in the repo.
  sourcemap: 'inline',
  // Deterministic output — bundle freshness hook relies on byte-identical
  // rebuilds from identical sources. esbuild is deterministic by default;
  // skipping minification keeps the bundle human-readable for diff review.
  minify: false,
  legalComments: 'inline',
  // Banner pins the bundle to its source — reviewers spot a stale bundle
  // by comparing the SHA to the working tree.
  banner: { js: `/* Auto-generated by tools/build-runtime.js — DO NOT EDIT.\n   Source: lib/runtime/index.js (and lib/transformers/*).\n   Rebuild: npm run runtime:build\n*/` },
};

async function buildOnce(outFile) {
  await esbuild.build({ ...BUILD_OPTIONS, outfile: outFile });
}

async function main() {
  if (watch) {
    const ctx = await esbuild.context({ ...BUILD_OPTIONS, outfile: OUT_FILE });
    await ctx.watch();
    if (!silent) console.log(`[build-runtime] watching lib/runtime/ → ${path.relative(ROOT, OUT_FILE)}`);
    // ctx stays alive; process holds open via the active watcher
    return;
  }

  if (check) {
    // esbuild encodes source paths in the inline sourcemap RELATIVE TO the
    // outfile location, so a tmp-file build in /tmp produces different
    // sourcemap paths than the in-place build — even when the JS is
    // byte-identical. Writing the check tempfile next to the real output
    // keeps the relative-path encoding stable so diff only reports real drift.
    const tmp = `${OUT_FILE}.check.tmp`;
    let exitCode = 0;
    try {
      await buildOnce(tmp);
      try {
        execSync(`diff -q "${OUT_FILE}" "${tmp}"`, { stdio: 'pipe' });
        // Identical — bundle is fresh.
      } catch (_e) {
        console.error('✗ lattice-runtime.js is stale relative to lib/runtime/');
        console.error('  Run: npm run runtime:build');
        console.error('  Bypass (last resort): git commit --no-verify');
        exitCode = 1;
      }
    } finally {
      try { fs.unlinkSync(tmp); } catch (_e) { /* best effort */ }
    }
    process.exit(exitCode);
  }

  await buildOnce(OUT_FILE);
  if (!silent) {
    const bytes = fs.statSync(OUT_FILE).size;
    console.log(`[build-runtime] ${path.relative(ROOT, OUT_FILE)}  (${(bytes / 1024).toFixed(1)} KB)`);
  }
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
