#!/usr/bin/env node
/**
 * Generate dist/docs/forms.json — the machine-readable catalog of Lattice's
 * Form composition model (Frame + Cell + Tile), beside dist/docs/components.json.
 * Also runs the **manifest↔CSS consistency gate** (the "light" coupling of
 * engineering/decisions/2026-06-16-form-manifest-medium-independent-contract.md
 * §4.2): every Cell geometry/gap CSS-token ref must be defined in lib CSS, else
 * the build fails — so a renamed token can't leave a manifest pointing at nothing.
 *
 * Mirrors tools/build-docs-portal.js (HARD RULE 15 — reuse the generator
 * pattern): load the manifests via the shared loader (lib/forms), project them
 * into one flat deterministic document, and gate freshness with --check. The
 * source of truth is lib/forms/{frame,tile,cell}/**; this file is generated, so
 * never hand-edit dist/docs/forms.json. Wired into tools/build.js after the
 * component doc portal.
 *
 * Usage:
 *   node tools/build-forms.js            # regenerate dist/docs/forms.json
 *   node tools/build-forms.js --check    # verify it is fresh (CI gate); exit 1 if stale
 *
 * See design/forms.md §11 and engineering/decisions/2026-06-15-form-implementation.md §6.
 */

const fs = require('node:fs');
const path = require('node:path');
const { loadCatalog, frameToggleSkip, checkManifestCssRefs } = require('../lib/forms');

const ROOT = path.join(__dirname, '..');
const DOCS_DIR = path.join(ROOT, 'dist', 'docs');
const JSON_FILE = path.join(DOCS_DIR, 'forms.json');
const LIB_DIR = path.join(ROOT, 'lib');

// Every `--name` custom property DEFINED (name immediately followed by `:`) in
// any source CSS under lib/. This is the 2D CSS renderer's token vocabulary; the
// manifest↔CSS gate (below) asserts every Cell geometry/gap ref resolves into it.
// Definitions only — `var(--x)` usages have `)` not `:` after the name, so they
// don't match. Scanning source (not dist/) keeps the gate decoupled from the
// build artifact.
function collectDefinedCssTokens() {
  const defined = new Set();
  const DEF = /(--[a-z0-9-]+)\s*:/gi;
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const abs = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(abs);
      else if (entry.name.endsWith('.css')) {
        // Strip /* … */ comments first so a token name mentioned in a comment
        // (e.g. `/* No --mark-todo: … */`) can't masquerade as a definition —
        // keeps the "defined" set honest to its name.
        const css = fs.readFileSync(abs, 'utf8').replace(/\/\*[\s\S]*?\*\//g, '');
        for (const m of css.matchAll(DEF)) defined.add(m[1]);
      }
    }
  };
  walk(LIB_DIR);
  return defined;
}

// The manifest↔CSS consistency gate (the "light" coupling that makes the Form
// catalog load-bearing — 2026-06-16-form-manifest-medium-independent-contract.md
// §4). Throws with every drift listed; called before generate AND --check so a
// broken ref fails loud, like the component ownership guard.
function assertManifestCssConsistency(cells) {
  const errors = checkManifestCssRefs(cells, collectDefinedCssTokens());
  if (errors.length) {
    throw new Error(`Form manifest↔CSS consistency failed:\n  ${errors.join('\n  ')}`);
  }
}

function renderJson() {
  const { cells, frames, tiles } = loadCatalog();
  const doc = {
    $comment: 'Generated by tools/build-forms.js from lib/forms/{frame,tile,cell}/** — do not edit by hand. The machine-readable catalog of the Form composition model (Frame + Cell + Tile). See design/forms.md §11.',
    model: 'Form 1.0',
    modelHref: 'https://github.com/slidewright/lattice/blob/main/design/forms.md',
    counts: { frames: frames.length, cells: cells.length, tiles: tiles.length },
    // The engine's chrome-skip set, derived from the frame manifests.
    formToggleSkip: frameToggleSkip(frames),
    frames,
    cells,
    tiles,
  };
  return `${JSON.stringify(doc, null, 2)}\n`;
}

function isStale(file, content) {
  const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
  return current !== content;
}

function main(argv) {
  const check = argv.includes('--check');
  // Gate first: a manifest↔CSS drift fails loud before we touch the catalog.
  assertManifestCssConsistency(loadCatalog().cells);
  const json = renderJson();
  fs.mkdirSync(DOCS_DIR, { recursive: true });
  const label = 'dist/docs/forms.json';
  if (check) {
    if (isStale(JSON_FILE, json)) {
      process.stderr.write(`stale: ${label} — run \`node tools/build-forms.js\` to regenerate.\n`);
      return 1;
    }
    process.stdout.write('forms catalog up to date.\n');
    return 0;
  }
  if (isStale(JSON_FILE, json)) {
    fs.writeFileSync(JSON_FILE, json);
    process.stdout.write(`wrote ${label}\n`);
  } else {
    process.stdout.write('no changes (forms catalog up to date).\n');
  }
  return 0;
}

if (require.main === module) {
  try {
    process.exit(main(process.argv.slice(2)));
  } catch (e) {
    // Clean gate failure (e.g. manifest↔CSS drift) — message, not a raw stack.
    process.stderr.write(`${e.message}\n`);
    process.exit(1);
  }
}

module.exports = { renderJson, JSON_FILE, collectDefinedCssTokens, assertManifestCssConsistency };
