#!/usr/bin/env node
/**
 * CSS bundler. Concatenates lib/_*.css + lib/components/<name>/styles.css
 * into the shipped lattice.css.
 *
 * Source order (declared below):
 *   1. lib/_theme.css            Marp @theme directive + header comment
 *   2. lib/_root.css             :root tokens + @import (must be near
 *                                top of the bundle so @import isn't
 *                                silently ignored as mid-file per spec)
 *   3. lib/_base.css             semantic HTML defaults (section, h*, p)
 *   4. lib/_scaffold.css         section, header, footer, pagination
 *   5. (@layer declaration emitted here)
 *   6. lib/components/<a..z>/styles.css   per-component, alphabetical
 *   7. lib/_modifiers.css        cross-cutting modifiers (subtitle,
 *                                eyebrow, key insight, pill, dark variant,
 *                                annotation, below-note, mirror, numbered,
 *                                .overflow, .heat, KaTeX-in-non-math)
 *   8. lib/_syntax-highlight.css highlight.js token theme
 *   9. lib/_chart-family.css     shared chart-frame chrome + .chart-status
 *                                vocabulary (progress / kanban / timeline-list)
 *  10. lib/_backgrounds.css      27 utility classes (16 gradients + 11 marks)
 *  11. lib/_semi-universal.css   compact, loose, accent
 *  12. lib/_universal.css        dark, with-period, bg-*, state, tone, chrome
 *  13. lib/_diagram-overrides.css  Mermaid SVG theme overrides
 *
 * lib/_legacy.css was retired on this branch — every block was either
 * moved to its proper destination above or deleted as dead documentation
 * comment. The file no longer exists.
 *
 * Missing source files are silently skipped — this lets the bundler
 * ramp up during per-component migration and allows downstream forks
 * to omit files they don't use.
 *
 * Usage:
 *   node tools/build-css.js          # write lattice.css
 *   node tools/build-css.js --check  # exit 1 if stale (CI gate)
 *   npm run css:build / css:check
 *
 * See docs/design-system.md §10.
 */

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const OUTPUT = path.join(ROOT, 'lattice.css');

const HEAD_SOURCES = ['lib/_theme.css', 'lib/_root.css', 'lib/_base.css', 'lib/_scaffold.css'];

// Bundle order = cascade order — later sources beat earlier ones at
// equal specificity. The middle tier (components, modifiers, shared
// frames, backgrounds) was carved out of the retired lib/_legacy.css
// across Phases 2-7; each source's bundle position preserves the
// cascade outcome those rules had when they lived in _legacy.css.
//
// @layer is declared below but inactive (kept for future use). Wrapping
// the current sources in @layer would reverse the cascade for any
// !important declarations, causing silent regressions; the historical
// _legacy.css had hundreds of such rules. Once the surviving
// !important declarations are audited and removed, @layer can activate.

// Cross-cutting modifiers (subtitle, eyebrow, key insight, universal
// pill, dark variant, below-note, annotation, mirror, numbered,
// .overflow, .heat, KaTeX-in-non-math). Bundled AFTER per-component
// styles so modifier defaults compose on top of components.
const MODIFIERS_SOURCE = 'lib/_modifiers.css';
// highlight.js token theme — wires .hljs-* to the --hljs-* tokens.
const SYNTAX_HIGHLIGHT_SOURCE = 'lib/_syntax-highlight.css';
// Shared chart-frame chrome + .chart-status pill vocabulary, shared
// by gantt, radar, quadrant, progress, piechart, kanban, timeline-list.
const CHART_FAMILY_SOURCE = 'lib/_chart-family.css';
// 27 utility classes (16 gradient accents + 11 SVG accent marks) for
// peripheral atmospheric accents. All palette-blind via var(--accent).
const BACKGROUNDS_SOURCE = 'lib/_backgrounds.css';
const TAIL_SOURCES = [
  'lib/_semi-universal.css',
  'lib/_universal.css',
  'lib/_diagram-overrides.css',
];

const LAYER_DECLARATION =
  '@layer base, root, scaffold, components, semi-universal, universal, diagram-overrides;';

const BANNER = [
  '/* lattice.css — GENERATED by tools/build-css.js.',
  ' * Do not edit by hand. Re-run `npm run css:build` after touching',
  ' * any source file in lib/_*.css or lib/components/<name>/styles.css.',
  ' * CI gate: `npm run css:check`.',
  ' */',
  '',
].join('\n');

function readIfExists(rel) {
  const abs = path.join(ROOT, rel);
  if (!fs.existsSync(abs)) return null;
  return fs.readFileSync(abs, 'utf8').replace(/\s+$/, '') + '\n';
}

function componentStyles() {
  const dir = path.join(ROOT, 'lib', 'components');
  if (!fs.existsSync(dir)) return [];
  const names = fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();
  const out = [];
  for (const name of names) {
    // Dotted convention: <name>.styles.css; tolerate legacy styles.css too.
    const dotted = path.join('lib', 'components', name, `${name}.styles.css`);
    const legacy = path.join('lib', 'components', name, 'styles.css');
    const dottedText = readIfExists(dotted);
    if (dottedText) {
      out.push({ rel: dotted, text: dottedText });
      continue;
    }
    const legacyText = readIfExists(legacy);
    if (legacyText) out.push({ rel: legacy, text: legacyText });
  }
  return out;
}

function bundle() {
  const parts = [BANNER];
  // Marp @theme must come before any @layer or other at-rule that
  // affects parsing, so HEAD sources come first.
  for (const rel of HEAD_SOURCES) {
    const text = readIfExists(rel);
    if (text) {
      parts.push(`/* === ${rel} === */`);
      parts.push(text);
    }
  }
  // Declare the cascade once for the whole bundle (reserved for future
  // use — see file header for why @layer is inactive today).
  parts.push(LAYER_DECLARATION);
  parts.push('');
  // Per-component CSS, alphabetical. Component selectors are typically
  // section.X > … (0,1,N+) which beats the modifier defaults below at
  // higher specificity. At equal specificity, modifiers win source-
  // order — that's why modifiers come after.
  for (const { rel, text } of componentStyles()) {
    parts.push(`/* === ${rel} === */`);
    parts.push(text);
  }
  // Cross-cutting modifiers. AFTER components so equal-specificity
  // collisions resolve to modifier defaults. Component variants that
  // want to override (e.g. citation-card.pull-quote.pull-quote > blockquote
  // ::before) bump specificity in their own component file.
  const modifiers = readIfExists(MODIFIERS_SOURCE);
  if (modifiers) {
    parts.push(`/* === ${MODIFIERS_SOURCE} === */`);
    parts.push(modifiers);
  }
  const syntax = readIfExists(SYNTAX_HIGHLIGHT_SOURCE);
  if (syntax) {
    parts.push(`/* === ${SYNTAX_HIGHLIGHT_SOURCE} === */`);
    parts.push(syntax);
  }
  const chartFamily = readIfExists(CHART_FAMILY_SOURCE);
  if (chartFamily) {
    parts.push(`/* === ${CHART_FAMILY_SOURCE} === */`);
    parts.push(chartFamily);
  }
  const backgrounds = readIfExists(BACKGROUNDS_SOURCE);
  if (backgrounds) {
    parts.push(`/* === ${BACKGROUNDS_SOURCE} === */`);
    parts.push(backgrounds);
  }
  // Tail: semi-universal → universal → diagram overrides. Each later
  // tier wins over earlier tiers by source order.
  for (const rel of TAIL_SOURCES) {
    const text = readIfExists(rel);
    if (text) {
      parts.push(`/* === ${rel} === */`);
      parts.push(text);
    }
  }
  return parts.join('\n');
}

function main(argv) {
  const fresh = bundle();
  if (argv.includes('--check')) {
    const current = fs.existsSync(OUTPUT) ? fs.readFileSync(OUTPUT, 'utf8') : '';
    if (current === fresh) {
      process.stdout.write('lattice.css is up to date.\n');
      return 0;
    }
    process.stderr.write('error: lattice.css is stale relative to sources.\n');
    process.stderr.write('       Run `npm run css:build` to regenerate.\n');
    return 1;
  }
  fs.writeFileSync(OUTPUT, fresh);
  process.stdout.write(`wrote lattice.css (${fresh.length.toLocaleString()} bytes)\n`);
  return 0;
}

if (require.main === module) process.exit(main(process.argv.slice(2)));

module.exports = { bundle, main, OUTPUT };
