#!/usr/bin/env node
/**
 * CSS bundler. Concatenates lib/_*.css + lib/components/<name>/styles.css
 * into the shipped lattice.css.
 *
 * Source order (declared below):
 *   1. lib/_theme.css            Marp @theme directive + header comment
 *   2. lib/_root.css             :root tokens + @import (must be near
 *                                top of the bundle so @import isn't
 *                                silently ignored as mid-file per spec)
 *   3. lib/_base.css             semantic HTML defaults (section, h*, p)
 *   4. lib/_scaffold.css         section, header, footer, pagination
 *   5. (@layer declaration emitted here)
 *   6. lib/components/<a..z>/styles.css   per-component, alphabetical
 *   7. lib/_legacy.css           residual non-extracted rules from old lattice.css
 *   8. lib/_semi-universal.css   compact, loose, accent
 *   9. lib/_universal.css        dark, with-period, bg-*, state, tone, chrome
 *  10. lib/_diagram-overrides.css  Mermaid theme overrides
 *
 * Missing source files are silently skipped — this lets the bundler
 * ramp up during the per-component migration (lib/components per-folder
 * styles.css files start empty; lib/_universal.css etc. land one at a time).
 *
 * Usage:
 *   node tools/build-css.js          # write lattice.css
 *   node tools/build-css.js --check  # exit 1 if stale (CI gate)
 *   npm run css:build / css:check
 *
 * See docs/design-system.md §10.
 */

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const OUTPUT = path.join(ROOT, 'lattice.css');

const HEAD_SOURCES = ['lib/_theme.css', 'lib/_root.css', 'lib/_base.css', 'lib/_scaffold.css'];
// Bundle order. Source order = cascade order — later sources beat
// earlier ones at equal specificity. Per-component styles come AFTER
// _legacy.css so component overrides win; _universal.css comes after
// the components so universal variants beat component base rules.
//
// _legacy.css contains hundreds of !important rules that historically
// beat both Marp's runtime scaffold AND each other via source-order
// cascade. Wrapping _legacy.css in @layer would demote those !important
// rules (the CSS @layer cascade REVERSES for !important), causing
// silent regressions. So @layer is NOT active here — the @layer
// declaration is reserved for future use once _legacy.css is fully
// extracted into proper layered files (then per-component and shared
// CSS can opt into @layer cleanly).
// Cross-cutting modifier rules (SUBTITLE / EYEBROW / KEY INSIGHT /
// UNIVERSAL PILL / DARK VARIANT / BELOW-NOTE / ANNOTATION). Bundled
// AFTER per-component styles so modifier defaults compose on top of
// components, BEFORE _legacy.css so the cascade outcome matches the
// pre-extraction state (modifiers used to live at the top of
// _legacy.css; same position in the bundle now). KEY INSIGHT's
// selector is wrapped in :where() inside the file so component-specific
// blockquote::before rules can override it on specificity, not source
// order — see the cards-side / citation-card / redline extraction
// notes for the cascade-collision history.
const MODIFIERS_SOURCE = 'lib/_modifiers.css';
const LEGACY_SOURCE = 'lib/_legacy.css';
const TAIL_SOURCES = [
  'lib/_semi-universal.css',
  'lib/_universal.css',
  'lib/_diagram-overrides.css',
];

const LAYER_DECLARATION =
  '@layer base, root, scaffold, components, semi-universal, universal, diagram-overrides;';

const BANNER = [
  '/* lattice.css — GENERATED by tools/build-css.js.',
  ' * Do not edit by hand. Re-run `npm run css:build` after touching',
  ' * any source file in lib/_*.css or lib/components/<name>/styles.css.',
  ' * CI gate: `npm run css:check`.',
  ' */',
  '',
].join('\n');

function readIfExists(rel) {
  const abs = path.join(ROOT, rel);
  if (!fs.existsSync(abs)) return null;
  return fs.readFileSync(abs, 'utf8').replace(/\s+$/, '') + '\n';
}

function componentStyles() {
  const dir = path.join(ROOT, 'lib', 'components');
  if (!fs.existsSync(dir)) return [];
  const names = fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();
  const out = [];
  for (const name of names) {
    const rel = path.join('lib', 'components', name, 'styles.css');
    const text = readIfExists(rel);
    if (text) out.push({ rel, text });
  }
  return out;
}

function bundle() {
  const parts = [BANNER];
  // Marp @theme must come before any @layer or other at-rule that
  // affects parsing, so HEAD sources come first.
  for (const rel of HEAD_SOURCES) {
    const text = readIfExists(rel);
    if (text) {
      parts.push(`/* === ${rel} === */`);
      parts.push(text);
    }
  }
  // Declare the cascade once for the whole bundle (reserved for future
  // use; see comment on LEGACY_SOURCE about why @layer is inactive).
  parts.push(LAYER_DECLARATION);
  parts.push('');
  // Per-component CSS, alphabetical. Comes BEFORE _legacy so cross-
  // cutting modifier rules in _legacy (accent, compact, mirror, etc.)
  // continue to override component base rules via source order — the
  // historical cascade pattern of "layouts first, modifiers last."
  // Per-component selectors win their own base properties via
  // specificity (section.foo > section).
  for (const { rel, text } of componentStyles()) {
    parts.push(`/* === ${rel} === */`);
    parts.push(text);
  }
  // Cross-cutting modifiers (post-Phase-5a). Bundled here so they sit
  // in the SAME bundle position the modifier blocks occupied when they
  // were at the top of _legacy.css — preserves the existing cascade
  // for every still-in-_legacy component rule. Component-extracted
  // rules can still override KEY INSIGHT chrome via specificity (the
  // KEY INSIGHT selector is :where()-wrapped in this file).
  const modifiers = readIfExists(MODIFIERS_SOURCE);
  if (modifiers) {
    parts.push(`/* === ${MODIFIERS_SOURCE} === */`);
    parts.push(modifiers);
  }
  // Legacy monolith — residual scaffold + un-extracted component CSS.
  // Source order is the cascade order. After Phase 5a, this file no
  // longer contains the modifier blocks (those moved to _modifiers.css
  // above).
  const legacy = readIfExists(LEGACY_SOURCE);
  if (legacy) {
    parts.push(`/* === ${LEGACY_SOURCE} === */`);
    parts.push(legacy);
  }
  // Tail: semi-universal → universal → diagram overrides. Each later
  // tier wins over earlier tiers by source order.
  for (const rel of TAIL_SOURCES) {
    const text = readIfExists(rel);
    if (text) {
      parts.push(`/* === ${rel} === */`);
      parts.push(text);
    }
  }
  return parts.join('\n');
}

function main(argv) {
  const fresh = bundle();
  if (argv.includes('--check')) {
    const current = fs.existsSync(OUTPUT) ? fs.readFileSync(OUTPUT, 'utf8') : '';
    if (current === fresh) {
      process.stdout.write('lattice.css is up to date.\n');
      return 0;
    }
    process.stderr.write('error: lattice.css is stale relative to sources.\n');
    process.stderr.write('       Run `npm run css:build` to regenerate.\n');
    return 1;
  }
  fs.writeFileSync(OUTPUT, fresh);
  process.stdout.write(`wrote lattice.css (${fresh.length.toLocaleString()} bytes)\n`);
  return 0;
}

if (require.main === module) process.exit(main(process.argv.slice(2)));

module.exports = { bundle, main, OUTPUT };
