#!/usr/bin/env node
/**
 * Generate dist/docs/forms.json — the machine-readable catalog of Lattice's
 * Form composition model (Frame + Cell + Tile), beside dist/docs/components.json.
 *
 * Mirrors tools/build-docs-portal.js (HARD RULE 15 — reuse the generator
 * pattern): load the manifests via the shared loader (lib/forms), project them
 * into one flat deterministic document, and gate freshness with --check. The
 * source of truth is lib/forms/{frame,tile,cell}/**; this file is generated, so
 * never hand-edit dist/docs/forms.json. Wired into tools/build.js after the
 * component doc portal.
 *
 * Usage:
 *   node tools/build-forms.js            # regenerate dist/docs/forms.json
 *   node tools/build-forms.js --check    # verify it is fresh (CI gate); exit 1 if stale
 *
 * See design/forms.md §11 and engineering/decisions/2026-06-15-form-implementation.md §6.
 */

const fs = require('node:fs');
const path = require('node:path');
const { loadCatalog, frameToggleSkip } = require('../lib/forms');

const ROOT = path.join(__dirname, '..');
const DOCS_DIR = path.join(ROOT, 'dist', 'docs');
const JSON_FILE = path.join(DOCS_DIR, 'forms.json');

function renderJson() {
  const { cells, frames, tiles } = loadCatalog();
  const doc = {
    $comment: 'Generated by tools/build-forms.js from lib/forms/{frame,tile,cell}/** — do not edit by hand. The machine-readable catalog of the Form composition model (Frame + Cell + Tile). See design/forms.md §11.',
    model: 'Form 1.0',
    modelHref: 'https://github.com/slidewright/lattice/blob/main/design/forms.md',
    counts: { frames: frames.length, cells: cells.length, tiles: tiles.length },
    // The engine's chrome-skip set, derived from the frame manifests.
    formToggleSkip: frameToggleSkip(frames),
    frames,
    cells,
    tiles,
  };
  return `${JSON.stringify(doc, null, 2)}\n`;
}

function isStale(file, content) {
  const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
  return current !== content;
}

function main(argv) {
  const check = argv.includes('--check');
  const json = renderJson();
  fs.mkdirSync(DOCS_DIR, { recursive: true });
  const label = 'dist/docs/forms.json';
  if (check) {
    if (isStale(JSON_FILE, json)) {
      process.stderr.write(`stale: ${label} — run \`node tools/build-forms.js\` to regenerate.\n`);
      return 1;
    }
    process.stdout.write('forms catalog up to date.\n');
    return 0;
  }
  if (isStale(JSON_FILE, json)) {
    fs.writeFileSync(JSON_FILE, json);
    process.stdout.write(`wrote ${label}\n`);
  } else {
    process.stdout.write('no changes (forms catalog up to date).\n');
  }
  return 0;
}

if (require.main === module) process.exit(main(process.argv.slice(2)));

module.exports = { renderJson, JSON_FILE };
