#!/usr/bin/env node
/**
 * CSS bundler. Concatenates lib/_*.css + lib/components/<name>/styles.css
 * into the shipped lattice.css.
 *
 * Source order (declared below):
 *   1. lib/_theme.css            Marp @theme directive + header comment
 *   2. lib/_root.css             :root tokens, preceded by the GENERATED
 *                                self-hosted @font-face block (from
 *                                lib/fonts/text-faces.js — no CDN @import)
 *   3. lib/_base.css             semantic HTML defaults (section, h*, p)
 *   4. lib/_scaffold.css         section, header, footer, pagination
 *   5. (@layer declaration emitted here)
 *   6. lib/components/<a..z>/styles.css   per-component, alphabetical
 *   7. lib/_modifiers.css        cross-cutting modifiers (subtitle,
 *                                eyebrow, key insight, pill, dark variant,
 *                                annotation, below-note, mirror, numbered,
 *                                .overflow, .heat, KaTeX-in-non-math)
 *   8. lib/_syntax-highlight.css highlight.js token theme
 *   9. lib/_chart-family.css     shared chart-frame chrome + .chart-status
 *                                vocabulary (progress / kanban / timeline-list)
 *  10. lib/base/base.treatments.css  27 utility classes (12 tints + 11 marks + reset)
 *  10b. lib/base/base.sketch.css  the `sketch` finish modifier (hand-drawn skin)
 *  11. lib/_semi-universal.css   compact, loose, accent
 *  12. lib/_universal.css        dark, with-period, tint-*, mark-*, state, tone, chrome
 *  13. lib/_diagram-overrides.css  Mermaid SVG theme overrides
 *
 * lib/_legacy.css was retired on this branch — every block was either
 * moved to its proper destination above or deleted as dead documentation
 * comment. The file no longer exists.
 *
 * Missing source files are silently skipped — this lets the bundler
 * ramp up during per-component migration and allows downstream forks
 * to omit files they don't use.
 *
 * Usage:
 *   node tools/build-css.js          # write lattice.css
 *   node tools/build-css.js --check  # exit 1 if stale (CI gate)
 *   npm run css:build / css:check
 *
 * See design/design-system.md §10.
 */

const fs = require('node:fs');
const path = require('node:path');
const { minifyCss } = require('./minify-css');
const { typographyTokensCss } = require('../lib/typography/emit');
const { TEXT_FACES } = require('../lib/fonts/text-faces');

const ROOT = path.join(__dirname, '..');
const OUTPUT = path.join(ROOT, 'dist', 'lattice.css');
const MIN_OUTPUT = path.join(ROOT, 'dist', 'lattice.min.css');
const MIN_BANNER = '/* dist/lattice.min.css — GENERATED by tools/build-css.js (minified). Do not edit. */';

// Self-hosted fonts: the woff2 source-of-truth (assets/fonts/, not in the
// tarball) is copied to dist/fonts/ (shipped) at build time, and the bundle
// references them with stylesheet-relative `fonts/<file>.woff2` URLs. KaTeX's
// own glyph woff2 land in the same dir so math is offline too. Zero network.
const ASSET_FONTS = path.join(ROOT, 'assets', 'fonts');
const DIST_FONTS = path.join(ROOT, 'dist', 'fonts');
const EMOJI_CSS_OUTPUT = path.join(ROOT, 'dist', 'lattice-emoji.css');

// Per-palette minified theme variants. The Export-to-Marp bundle (lib/core/
// marp-bundle.js) ships these so a recipient's marp-cli / VS Code render carries
// the same minified palette the playground serves — built here, in one place,
// alongside lattice.min.css so the @theme/@import-preservation rule lives once.
const THEMES_SRC = path.join(ROOT, 'themes');
const DIST_THEMES = path.join(ROOT, 'dist', 'themes');
const themeMinBanner = (name) =>
  `/* dist/themes/${name}.min.css — GENERATED by tools/build-css.js (minified). Do not edit. */`;

// { '<name>.min.css': minifiedContent } for every themes/*.css, @theme/@import intact.
function buildThemes() {
  const out = {};
  for (const file of fs.readdirSync(THEMES_SRC).sort()) {
    if (!file.endsWith('.css')) continue;
    const name = file.replace(/\.css$/, '');
    const src = fs.readFileSync(path.join(THEMES_SRC, file), 'utf8');
    out[`${name}.min.css`] = minifyCss(src, themeMinBanner(name)) + '\n';
  }
  return out;
}

const HEAD_SOURCES = [
  'lib/_theme.css',
  'lib/base/base.tokens.css',
  'lib/base/base.elements.css',
  'lib/integrations/markdown-it/scaffold.css',
];

// Bundle order = cascade order — later sources beat earlier ones at
// equal specificity. The middle tier (components, modifiers, shared
// frames, backgrounds) was carved out of the retired lib/_legacy.css
// across Phases 2-7; each source's bundle position preserves the
// cascade outcome those rules had when they lived in _legacy.css.
//
// @layer is declared below but inactive (kept for future use). Wrapping
// the current sources in @layer would reverse the cascade for any
// !important declarations, causing silent regressions; the historical
// _legacy.css had hundreds of such rules. Once the surviving
// !important declarations are audited and removed, @layer can activate.

// Cross-cutting modifiers (subtitle, eyebrow, key insight, universal
// pill, dark variant, below-note, annotation, mirror, numbered,
// .overflow, .heat, KaTeX-in-non-math). Bundled AFTER per-component
// styles so modifier defaults compose on top of components.
const MODIFIERS_SOURCE = 'lib/base/base.modifiers.css';
// highlight.js token theme — wires .hljs-* to the --hljs-* tokens.
const SYNTAX_HIGHLIGHT_SOURCE = 'lib/integrations/highlight-js/highlight-js.css';
// Shared chart-frame chrome + .chart-status pill vocabulary, shared
// by gantt, radar, quadrant, progress, piechart, kanban, timeline-list.
// Lives in the chart bucket under an underscore-prefixed folder
// (skipped by the component loader and the bucket-wide CSS walker).
const CHART_FAMILY_SOURCE = 'lib/components/chart/_chart-family/chart-family.css';
// 27 utility classes (12 tints + 11 marks + treatment-none reset) for
// peripheral atmospheric accents. All palette-blind via var(--accent).
const TREATMENTS_SOURCE = 'lib/base/base.treatments.css';
// Parametric full-bleed FINISH backdrops (the `field` zone of the Finish
// family): pure-gradient, palette-blind, export-safe surface treatments selected
// deck-wide via the `finish:` register or per-slide via `_class: backdrop …`.
// Bundled immediately after treatments so it shares the compositor's two slots
// (the compositor selector matches `.backdrop`). See base.backdrops.css.
const BACKDROPS_SOURCE = 'lib/base/base.backdrops.css';
// Focus & highlighting — the `.lat-focus` / `.lat-recede` treatment contract
// (content-aware default by axis + spotlight/ring/list-fill variants), keyed on
// the tags the focus resolver (lib/transformers/focus.js) stamps. Palette-blind
// via var(--focus-*). Cross-cutting universal feature, bundled alongside the
// treatments tier so it composes over every component. See
// engineering/decisions/2026-06-16-focus-highlighting.md.
const FOCUS_SOURCE = 'lib/base/base.focus.css';
// Narrative build — the progressive-disclosure reveal contract (`data-build-step`
// + `.lat-built`, gated on a consumer-set `data-build-at`). Palette-blind; bundled
// alongside focus (its temporal cousin). 0-pixel without `data-build-at`. See
// engineering/decisions/2026-06-16-narrative-step-spec.md.
const BUILD_SOURCE = 'lib/base/base.build.css';
// The `sketch` finish modifier — hand-drawn skin (handwriting + drawn
// boxes), palette-blind via var(--…). Tail tier so its section.sketch …
// selectors compose on top of every component. See lib/base/base.sketch.css.
const SKETCH_SOURCE = 'lib/base/base.sketch.css';
// Self-contained Form CSS — every lib/forms/{cell,tile}/<id>/<id>.css. A Cell or
// Tile that owns its CSS (issue #356, the self-containment reframing) drops a
// sheet in its folder; the build picks it up by glob, so adding/removing a Cell
// or Tile folder needs no edit to this list. Both are bundled immediately after
// base.variants and before components — the exact slot these rules held when they
// lived inline in base.variants.css, so the cascade is unchanged. Cells come
// before Tiles (the order the rules had in base.variants — the Cell is the slot,
// the Tile docks into it); the two sets target disjoint selectors, so the order
// is cascade-neutral regardless.
function formCssSources(noun) {
  const dir = path.join(ROOT, 'lib', 'forms', noun);
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory() && !d.name.startsWith('_'))
    .map((d) => `lib/forms/${noun}/${d.name}/${d.name}.css`)
    .filter((rel) => fs.existsSync(path.join(ROOT, rel)))
    .sort();
}
const FORMS_CELL_CSS_SOURCES = formCssSources('cell');
const FORMS_TILE_CSS_SOURCES = formCssSources('tile');

const TAIL_SOURCES = [
  'lib/shared/shared.styles.css',
  'lib/base/base.variants.css',
  ...FORMS_CELL_CSS_SOURCES,
  ...FORMS_TILE_CSS_SOURCES,
  'lib/integrations/mermaid/mermaid.css',
  // Fluid-box viewer mode — inert unless :root[data-lattice-view="fluid"] is set
  // (lattice-emulator --fluid + the runtime fluid controller). Last so its
  // viewport-box override also wins on source order, not just specificity.
  'lib/base/base.fluid-view.css',
];

const LAYER_DECLARATION =
  '@layer base, root, scaffold, components, semi-universal, universal, diagram-overrides;';

const BANNER = [
  '/* dist/lattice.css — GENERATED by tools/build-css.js.',
  ' * Do not edit by hand. Re-run `npm run css:build` after touching',
  ' * any source file in lib/_*.css or lib/components/<name>/styles.css.',
  ' * CI gate: `npm run css:check`.',
  ' */',
  '',
].join('\n');

function readIfExists(rel) {
  const abs = path.join(ROOT, rel);
  if (!fs.existsSync(abs)) return null;
  return fs.readFileSync(abs, 'utf8').replace(/\s+$/, '') + '\n';
}

// Per-family slicing CSS, GENERATED from each Frame manifest's `slicing` block
// (the responsive-Frame contract, 2026-06-21-reflow-as-form-capability.md §7).
// Only the SAME-BAND half is CSS: a family's per-Cell `tokens` become a
// `[data-family]`-keyed rule that re-slices the band (e.g. --masthead-cols:1fr
// → masthead lede-over-bay at tall/strip). CROSS-BAND relocation (a `region`
// override) is NOT emitted here — the runtime moves the node (it can't be done
// in pure CSS without reviving section-as-grid). The runtime stamps data-family;
// an absent family = the default (wide/authored) look, so this is purely additive.
function formsSlicingCss() {
  const dir = path.join(ROOT, 'lib', 'forms', 'frame');
  if (!fs.existsSync(dir)) return null;
  const rules = [];
  const frames = fs.readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();
  for (const name of frames) {
    const mf = path.join(dir, name, `${name}.manifest.json`);
    if (!fs.existsSync(mf)) continue;
    const slicing = (JSON.parse(fs.readFileSync(mf, 'utf8')).slicing) || {};
    for (const fam of ['square', 'tall', 'strip']) {
      const famSlice = slicing[fam];
      if (!famSlice) continue;
      // Merge every Cell's per-family tokens into ONE section-scoped rule. Custom
      // properties INHERIT, so a token set on the section is read by each Cell's
      // element via its own `var(--token)` — `.cell-masthead`, but ALSO the footer
      // Cells whose elements are `.tile-progress` / `<footer>` / `::after` and have
      // no `.cell-<id>` wrapper to target. (Was `.cell-${cellId}`, which only
      // reached Cells that ARE a real `.cell-` element — masthead — and silently
      // missed the footer zones.) Token names are Cell-unique, so the merge can't
      // collide. See engineering/decisions/2026-06-21-reflow-as-form-capability.md §7.
      const decls = [];
      for (const cellId of Object.keys(famSlice).sort()) {
        const tokens = famSlice[cellId]?.tokens;
        if (!tokens) continue; // region-only entries are the runtime's job
        for (const t of Object.keys(tokens).sort()) decls.push(`${t}: ${tokens[t]};`);
      }
      if (decls.length) rules.push(`section.form[data-family="${fam}"] { ${decls.join(' ')} }`);
    }
  }
  return rules.length ? rules.join('\n') + '\n' : null;
}

// KaTeX base stylesheet — the math-glyph layout engine CSS. Unlike the other
// integrations (highlight-js, mermaid), whose lib/integrations/<name>/<name>.css
// is a hand-authored token map, KaTeX's base is the package's own ~720-selector
// layout sheet, so we vendor it from the installed `katex` package at build time
// (auto-synced — no stale committed blob). Its glyph fonts used to resolve to a
// pinned jsDelivr CDN; they are now SELF-HOSTED — we copy the package's woff2 to
// dist/fonts/ and rewrite each `@font-face` src down to the single woff2 entry,
// pointed at stylesheet-relative `fonts/<file>.woff2`. Math renders with zero
// network, same as the text faces. (woff2 is universally supported on every
// render path we target, so the woff/ttf fallbacks in KaTeX's src list are
// dropped rather than shipped.) See lib/integrations/katex/katex.docs.md.
function katexFontFiles() {
  try {
    const dir = path.dirname(require.resolve('katex/dist/katex.min.css'));
    return fs.readdirSync(path.join(dir, 'fonts')).filter((f) => f.endsWith('.woff2'));
  } catch (_e) {
    return [];
  }
}
function katexBaseCss() {
  let cssPath;
  try {
    cssPath = require.resolve('katex/dist/katex.min.css');
  } catch (_e) {
    return null; // katex not installed — math degrades to unstyled glyphs
  }
  const raw = fs.readFileSync(cssPath, 'utf8').replace(/\s+$/, '');
  // Collapse each `src:url(fonts/X.woff2) format("woff2"),url(...woff)...,url(...ttf)...`
  // down to just the local woff2 entry.
  const local = raw.replace(
    /src:url\(\s*(['"]?)fonts\/([^)'"]+\.woff2)\1\s*\)\s*format\((['"]?)woff2\3\)[^;}]*/g,
    "src:url('fonts/$2') format('woff2')",
  );
  return `${local}\n`;
}

// The self-hosted `@font-face` block that replaced the Google `@import`. Built
// from the canonical manifest; each face points at a stylesheet-relative
// dist/fonts/<file>.woff2. Injected at the base.tokens.css cascade slot.
function localFontFacesCss() {
  const faces = TEXT_FACES.map(
    ({ family, weight, style, file }) =>
      `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};` +
      `font-display:swap;src:url('fonts/${file}.woff2') format('woff2');}`,
  );
  return faces.join('\n');
}

// The opt-in "full offline" emoji stylesheet (dist/lattice-emoji.css). Tiny and
// committed so npm consumers have it; the ~25 MB Noto Color Emoji ttf it points
// at is fetched on demand by `npm run fonts:emoji` (excluded from the tarball).
// Until fetched, the reference is inert and colour emoji uses the system font.
function emojiFontFaceCss() {
  return (
    '/* dist/lattice-emoji.css — GENERATED by tools/build-css.js. Do not edit.\n' +
    ' * Opt-in full-offline colour emoji for air-gapped environments. Link this\n' +
    " * AFTER lattice.css and run `npm run fonts:emoji` to vendor the font (it is\n" +
    ' * excluded from the npm tarball at ~25 MB). Without it, emoji fall back to\n' +
    ' * the installed system emoji font. See assets/fonts/README.md. */\n' +
    "@font-face{font-family:'Noto Color Emoji';font-style:normal;font-weight:400;" +
    "font-display:swap;src:url('fonts/noto-color-emoji.ttf') format('truetype');}\n"
  );
}

// Copy the woff2 source-of-truth into dist/fonts/ (text faces from assets/fonts/,
// KaTeX glyphs from the package). Returns the set of filenames written so the
// caller can prune anything stale. Idempotent.
function syncDistFonts() {
  fs.mkdirSync(DIST_FONTS, { recursive: true });
  const written = new Set();
  for (const { file } of TEXT_FACES) {
    const name = `${file}.woff2`;
    fs.copyFileSync(path.join(ASSET_FONTS, name), path.join(DIST_FONTS, name));
    written.add(name);
  }
  // KaTeX is a hard dependency today, but guard the resolve like every sibling
  // (katexBaseCss/katexFontFiles/distFontsStale) so the bundle still builds —
  // sans math glyphs — if it ever goes missing, instead of crashing the build.
  try {
    const katexDir = path.dirname(require.resolve('katex/dist/katex.min.css'));
    for (const name of katexFontFiles()) {
      fs.copyFileSync(path.join(katexDir, 'fonts', name), path.join(DIST_FONTS, name));
      written.add(name);
    }
  } catch (_e) {
    /* katex absent — text faces still self-hosted; math degrades to unstyled */
  }
  // Prune orphaned woff2 (a removed face) but never touch a vendored emoji ttf.
  for (const f of fs.readdirSync(DIST_FONTS)) {
    if (f.endsWith('.woff2') && !written.has(f)) fs.rmSync(path.join(DIST_FONTS, f));
  }
  return written;
}

// True when dist/fonts/ is byte-identical to what syncDistFonts() would write
// (used by --check; pure read, no writes).
function distFontsStale() {
  const want = new Map();
  for (const { file } of TEXT_FACES) want.set(`${file}.woff2`, path.join(ASSET_FONTS, `${file}.woff2`));
  let katexDir;
  try {
    katexDir = path.dirname(require.resolve('katex/dist/katex.min.css'));
    for (const name of katexFontFiles()) want.set(name, path.join(katexDir, 'fonts', name));
  } catch (_e) {
    /* katex absent — only text faces required */
  }
  for (const [name, src] of want) {
    const dst = path.join(DIST_FONTS, name);
    if (!fs.existsSync(dst) || !fs.readFileSync(dst).equals(fs.readFileSync(src))) return true;
  }
  // An orphaned woff2 (manifest shrank) is also stale; emoji ttf is exempt.
  const have = fs.existsSync(DIST_FONTS) ? fs.readdirSync(DIST_FONTS).filter((f) => f.endsWith('.woff2')) : [];
  return have.some((f) => !want.has(f));
}

// Walk lib/components/ for per-component <name>.styles.css files. Tolerates
// three shapes during the Phase 3 disk-reorg migration:
//   1. Flat per-component:  lib/components/<name>/<name>.styles.css
//   2. Bucket-nested:       lib/components/<bucket>/<name>/<name>.styles.css
//   3. Legacy:              lib/components/<name>/styles.css
//
// A directory whose own <dirname>.styles.css exists is treated as a
// component (covers the `diagram` collision, where the component name
// matches a bucket name). Otherwise we treat it as a bucket and recurse
// one level. Sorting by component name keeps bundle order stable
// regardless of which bucket a component lives in.
function componentStyles() {
  const root = path.join(ROOT, 'lib', 'components');
  if (!fs.existsSync(root)) return [];
  const collected = new Map(); // name → { rel, text }

  function tryReadFor(parentRelDir, name) {
    if (collected.has(name)) return false;
    const dotted = path.join(parentRelDir, name, `${name}.styles.css`);
    const legacy = path.join(parentRelDir, name, 'styles.css');
    const dottedText = readIfExists(dotted);
    if (dottedText) {
      collected.set(name, { rel: dotted, text: dottedText });
      return true;
    }
    const legacyText = readIfExists(legacy);
    if (legacyText) {
      collected.set(name, { rel: legacy, text: legacyText });
      return true;
    }
    return false;
  }

  function isComponentDir(parentAbsDir, name) {
    return (
      fs.existsSync(path.join(parentAbsDir, name, `${name}.styles.css`)) ||
      fs.existsSync(path.join(parentAbsDir, name, 'styles.css'))
    );
  }

  const entries = fs.readdirSync(root, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (entry.name.startsWith('_')) continue;

    // Component directly under lib/components/ (flat or per-component).
    if (isComponentDir(root, entry.name)) {
      tryReadFor(path.join('lib', 'components'), entry.name);
      continue;
    }

    // Otherwise treat as a bucket and walk one level deeper.
    const bucketRel = path.join('lib', 'components', entry.name);
    const bucketDir = path.join(root, entry.name);
    const children = fs.readdirSync(bucketDir, { withFileTypes: true });
    for (const child of children) {
      if (!child.isDirectory()) continue;
      if (child.name.startsWith('_')) continue;
      tryReadFor(bucketRel, child.name);
    }
  }

  return [...collected.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([, v]) => v);
}

function bundle() {
  const parts = [BANNER];
  // Marp @theme must come before any @layer or other at-rule that
  // affects parsing, so HEAD sources come first.
  for (const rel of HEAD_SOURCES) {
    // The self-hosted @font-face block takes the cascade slot the Google
    // `@import` used to hold (top of base.tokens.css) — see lib/fonts/text-faces.js.
    if (rel === 'lib/base/base.tokens.css') {
      parts.push('/* === GENERATED lib/fonts/text-faces.js (self-hosted @font-face) === */');
      parts.push(localFontFacesCss());
    }
    const text = readIfExists(rel);
    if (text) {
      parts.push(`/* === ${rel} === */`);
      parts.push(text);
    }
    // The --fs-* typography tokens are GENERATED from the lib/typography/scale.js
    // manifest (curated landscape/square/portrait scales) — emitted right after
    // base.tokens.css so they sit in the HEAD token tier, before components, the
    // same cascade slot the hand-written block held.
    if (rel === 'lib/base/base.tokens.css') {
      parts.push('/* === GENERATED lib/typography/scale.js (--fs-* tokens) === */');
      parts.push(`${typographyTokensCss()}\n`);
    }
  }
  // KaTeX base layout sheet (vendored from the package). Early, before
  // components/modifiers, so lattice's own KaTeX tweaks (base.modifiers.css)
  // override the package defaults at source order.
  const katex = katexBaseCss();
  if (katex) {
    parts.push('/* === KaTeX base stylesheet — vendored from the katex package, fonts self-hosted → dist/fonts/ === */');
    parts.push(katex);
  }
  // Declare the cascade once for the whole bundle (reserved for future
  // use — see file header for why @layer is inactive today).
  parts.push(LAYER_DECLARATION);
  parts.push('');
  // Per-component CSS, alphabetical. Component selectors are typically
  // section.X > … (0,1,N+) which beats the modifier defaults below at
  // higher specificity. At equal specificity, modifiers win source-
  // order — that's why modifiers come after.
  for (const { rel, text } of componentStyles()) {
    parts.push(`/* === ${rel} === */`);
    parts.push(text);
  }
  // Cross-cutting modifiers. AFTER components so equal-specificity
  // collisions resolve to modifier defaults. Component variants that
  // want to override (e.g. citation-card.pull-quote.pull-quote > blockquote
  // ::before) bump specificity in their own component file.
  const modifiers = readIfExists(MODIFIERS_SOURCE);
  if (modifiers) {
    parts.push(`/* === ${MODIFIERS_SOURCE} === */`);
    parts.push(modifiers);
  }
  const syntax = readIfExists(SYNTAX_HIGHLIGHT_SOURCE);
  if (syntax) {
    parts.push(`/* === ${SYNTAX_HIGHLIGHT_SOURCE} === */`);
    parts.push(syntax);
  }
  const chartFamily = readIfExists(CHART_FAMILY_SOURCE);
  if (chartFamily) {
    parts.push(`/* === ${CHART_FAMILY_SOURCE} === */`);
    parts.push(chartFamily);
  }
  const treatments = readIfExists(TREATMENTS_SOURCE);
  if (treatments) {
    parts.push(`/* === ${TREATMENTS_SOURCE} === */`);
    parts.push(treatments);
  }
  const backdrops = readIfExists(BACKDROPS_SOURCE);
  if (backdrops) {
    parts.push(`/* === ${BACKDROPS_SOURCE} === */`);
    parts.push(backdrops);
  }
  const focus = readIfExists(FOCUS_SOURCE);
  if (focus) {
    parts.push(`/* === ${FOCUS_SOURCE} === */`);
    parts.push(focus);
  }
  const build = readIfExists(BUILD_SOURCE);
  if (build) {
    parts.push(`/* === ${BUILD_SOURCE} === */`);
    parts.push(build);
  }
  const sketch = readIfExists(SKETCH_SOURCE);
  if (sketch) {
    parts.push(`/* === ${SKETCH_SOURCE} === */`);
    parts.push(sketch);
  }
  // Tail: semi-universal → universal → diagram overrides. Each later
  // tier wins over earlier tiers by source order.
  for (const rel of TAIL_SOURCES) {
    const text = readIfExists(rel);
    if (text) {
      parts.push(`/* === ${rel} === */`);
      parts.push(text);
    }
  }
  // Generated last: the per-family slicing rules win on source order over the
  // Cell's own base rule (they also out-specify it via [data-family]).
  const slicing = formsSlicingCss();
  if (slicing) {
    parts.push('/* === generated: Form per-family slicing (frame manifests `slicing`) === */');
    parts.push(slicing);
  }
  return parts.join('\n');
}

function main(argv) {
  const fresh = bundle();
  const freshMin = minifyCss(fresh, MIN_BANNER) + '\n';
  const themes = buildThemes();
  const freshEmoji = emojiFontFaceCss();
  if (argv.includes('--check')) {
    const current = fs.existsSync(OUTPUT) ? fs.readFileSync(OUTPUT, 'utf8') : '';
    const currentMin = fs.existsSync(MIN_OUTPUT) ? fs.readFileSync(MIN_OUTPUT, 'utf8') : '';
    const currentEmoji = fs.existsSync(EMOJI_CSS_OUTPUT) ? fs.readFileSync(EMOJI_CSS_OUTPUT, 'utf8') : '';
    const themesStale = Object.entries(themes).some(([file, content]) => {
      const p = path.join(DIST_THEMES, file);
      return !fs.existsSync(p) || fs.readFileSync(p, 'utf8') !== content;
    });
    // A removed/renamed source theme leaves an orphaned dist file — also stale.
    const orphaned = fs.existsSync(DIST_THEMES)
      && fs.readdirSync(DIST_THEMES).some((f) => f.endsWith('.min.css') && !(f in themes));
    const fontsStale = distFontsStale();
    if (current === fresh && currentMin === freshMin && currentEmoji === freshEmoji
        && !themesStale && !orphaned && !fontsStale) {
      process.stdout.write(
        `lattice.css + lattice.min.css + lattice-emoji.css + dist/fonts/ + ${Object.keys(themes).length} dist/themes/*.min.css are up to date.\n`,
      );
      return 0;
    }
    process.stderr.write('error: lattice.css / lattice.min.css / lattice-emoji.css / dist/fonts/ / dist/themes/*.min.css is stale relative to sources.\n');
    process.stderr.write('       Run `npm run css:build` to regenerate.\n');
    return 1;
  }
  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, fresh);
  fs.writeFileSync(MIN_OUTPUT, freshMin);
  fs.writeFileSync(EMOJI_CSS_OUTPUT, freshEmoji);
  syncDistFonts();
  // Rewrite dist/themes/ wholesale so a removed source palette can't leave a stale file.
  fs.rmSync(DIST_THEMES, { recursive: true, force: true });
  fs.mkdirSync(DIST_THEMES, { recursive: true });
  for (const [file, content] of Object.entries(themes)) {
    fs.writeFileSync(path.join(DIST_THEMES, file), content);
  }
  process.stdout.write(
    `wrote dist/lattice.css (${fresh.length.toLocaleString()} bytes) + ` +
      `dist/lattice.min.css (${freshMin.length.toLocaleString()} bytes) + ` +
      `dist/lattice-emoji.css + dist/fonts/ + ` +
      `${Object.keys(themes).length} dist/themes/*.min.css\n`,
  );
  return 0;
}

if (require.main === module) process.exit(main(process.argv.slice(2)));

module.exports = { bundle, buildThemes, main, OUTPUT, MIN_OUTPUT, formsSlicingCss };
